To predict the resultant courese, first we need dataset for training the algorithm, so first we needed to generate the dataset from the url provided to us, ie. the url = 'https://alison.com/courses', to generate the dataset from the url we need to use the technique of web scraping, with the help of python the web scrapin tasks becomes easy, the only tough task is to determining and figure out what to scrap, in our case we need the course name because we need to predict the course name for the user input, and rest of all the content acording to the course name is the feature of the course( this feature will help us in the prediction process) and course name is the label for our dataset. after all the course name and the features into a csv file named 'alsiondataset1.csv' we are ready to proceede further. So lets loadd the dataset using pandas (i'm using Jupyter notebook to run my python code, you can use any but jupyter is good). Now we have the dataset, the dataset contains features and its label(course name), So first we will load the dataset and see aal the information related to the dataset. The below code loads the dataset and prints the number of messages in the dataset.

In [21]:
import pandas as pd
data = pd.read_csv('alsiondataset1.csv')

In [22]:
data = data[:995]
data

CourseName  \
0                                  Financial Literacy    
1                               Touch Typing Training    
2                   U.S. Citizenship Test Preparation    
3                   HIV/AIDS - Awareness & Prevention    
4     Microsoft Office Word 2007 تدريب باللغة العربية    
5                                 Drug-Free Workplace    
6                              Behaviour-Based Safety    
7                                         Back Safety    
8             ALISON ABC IT - Computer Training Suite    
9                             Fundamentals of Biology    
10       Microsoft Digital Literacy - Computer Basics    
11   An Introduction to Managing Safety and Health ...   
12   Get Safe - Work Safe - Safety and Health for S...   
13   Microsoft Digital Literacy - The Internet and ...   
14   Microsoft Digital Literacy - Productivity Prog...   
15   Safety and Health in the Technology Classroom ...   
16   Microsoft Digital Literacy - Computer Security...   
17    Microsoft Digital Literacy - Digital Lifestyles    
18   Safety and Health in the Science Laboratory fo...   
19                             Workstation Ergonomics    
20   Microsoft Digital Literacy - IT Basics, Intern...   
21   Managing Safety and Health in Schools (Interna...   
22                  Safety and Health in Construction    
23   Microsoft Digital Literacy (ARABIC) - Computer...   
24                           Fractions in Mathematics    
25   Microsoft Digital Literacy (ARABIC) - The Inte...   
26                             Algebra in Mathematics    
27              Probability and Chance in Mathematics    
28                          Fundamentals of Chemistry    
29                            Geometry in Mathematics    
..                                                 ...   
965       Introduction to Database Concepts - Revised    
966    Introduction to Strategic Management - Revised    
967  Applied Psychology - Understanding Models of C...   
968  Web Development - Advanced CSS3 Selectors and ...   
969  Design Thinking - Design Research and Analysis...   
970  Applied Operations Management - Introduction T...   
971  C# Programming - Coding with C# Syntax - Revised    
972  Applied Operations Management - Aggregate Plan...   
973  Understanding the Ebola Virus: History, Treatm...   
974          Aflatoun Refresher Training for Teachers    
975            Word 2016 - Features and Functionality    
976  ISO 14001:2015 - Environmental Management Syst...   
977  Databases - DML Statements and SQL Server Admi...   
978         Diploma in Communication Skills - Revised    
979  Applied Psychology - Understanding Consumer At...   
980  Applied Psychology - Matching Marketing Strate...   
981      JavaScript Application Programming - Revised    
982  JavaScript - Working with the Document Object ...   
983  C# Programming - Coding with C# Classes and Me...   
984  C# Programming - Switch Statements, Collection...   
985  Strategic Management - Decision Making Process...   
986  Applied Operations Management - Line Balancing...   
987         Swine Flu - Causes, Effects and Treatment    
988  Computer Networking - Local Area Networks and ...   
989  Wide Area Networks and Networking Services and...   
990  An Introduction to New Thinking for Your Class...   
991  HTML5 Game Development Working with Inventory ...   
992  Introduction to Games Development with HTML5 a...   
993  Nursing Studies - The Nurse as Team Leader and...   
994                              Understanding Brexit    

                                       0                               1  \
0                             Accounting                         Finance   
1                          Office Skills                          Typing   
2                           Study Skills                             NaN   
3                                    NaN                             NaN   
4                          Office Skills                Microsoft O

Now by using the descridbe method of the pandas we can know  the description of the dataset. Below shows the description of the message, and it shows differet property for label and message like count , unique , top and freq.
Till now our data looks something like below, and its seems large and disordered but dont worry we will process it in future code and will make better for our algorithm to easilly understand and predict.

In [23]:
data.describe()

CourseName            0        1  \
count                                         995          864      577   
unique                                        994          136      176   
top     Introduction to C# Programming - Revised   Programming  Finance   
freq                                            2           33       20   

                    2          3         4                 5  \
count             312        148        83                45   
unique            135         88        57                33   
top     Plant Biology  Evolution  Genetics  Hosting accounts   
freq                8          8         8                 4   

                            6           7           8  \
count                      32          24          16   
unique                     23          20          12   
top     HTML editing software  Index Page  HTML links   
freq                        4           4           4   

                              ...                          \
count                         ...                           
unique                        ...                           
top                           ...                           
freq                          ...                           

                              21               22              23          24  \
count                          3                2               2           1   
unique                         3                2               2           1   
top     Iris Scanning Technology  Backup hardware  Cyber Security  Biometrics   
freq                           1                1               1           1   

                                  25                         26  \
count                              1                          1   
unique                             1                          1   
top     Voice Recognition Technology  Fingerprinting technology   
freq                               1                          1   

                              27                        28       29  \
count                          1                         1        1   
unique                         1                         1        1   
top     Iris Scanning Technology  Productivity Improvement  MS Word   
freq                           1                         1        1   

                                                   Column  
count                                                 995  
unique                                                994  
top     Introduction to C# Programming - Revised  Prog...  
freq                                                    2  

[4 rows x 32 columns]

In [5]:
data['Column'][0]

'Financial Literacy  Accounting Finance Pensions Financial Accounting Financial Ratios                       '

Now we have to use the nltk library for removing stopwords and punctuation, because tstop words and punctuationa are useles for the algorithm because if will effect the efficency of our network prediction. And for this task nltk is the most popular library because of its accuracy and versitility.

In [6]:
import string
from nltk.corpus import stopwords


Let's make an function to remove all the stopwords and punctuation frpm all the rows of the features(text). so below is the function named text which takes input text of the row and process i and provide the output

In [7]:
def text(mess):
    mess = str(mess)
    n=[char for char in mess if char not in string.punctuation if char != 'NaN']
    
    n=''.join(n)
    
    cmess=[word for word in n.split() if word.lower() not in stopwords.words('english') ]
    
    return cmess

It's time to begin building your text classifier! The data has been loaded into a DataFrame called df. Explore it in the IPython Shell to investigate what columns you can use.

CountVectorizer will give identity to the text in the features which will help in the prediction process.
In this exercise, we'll use pandas alongside scikit-learn to create a sparse text vectorizer you can use to train and test a simple supervised model. To begin, you'll set up a CountVectorizer and investigate some of its features.

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
tf=CountVectorizer(analyzer=text).fit(data['Column'])

the below code with vocabulary_ will return that how many identity is assigned to the dataset

In [9]:
len(tf.vocabulary_)

1324

In [10]:
print(tf.get_feature_names()[10])

21


In [11]:
tmessage=tf.transform(data['Column'])

In [25]:
# print((100*tmessage.nnz)/(tmessage.shape[0]*tmessage.shape[1]))

In [88]:
from sklearn.feature_extraction.text import TfidfTransformer

In [39]:
fidtf=TfidfTransformer().fit(tmessage)

In [109]:
tf4=fidtf.transform(tmessage)
print(tf4)

  (0, 893)	0.2841173757081126
  (0, 794)	0.3029655289515394
  (0, 652)	0.24473050962259607
  (0, 432)	0.7341915288677883
  (0, 430)	0.19710615435732323
  (0, 27)	0.4355549857376911
  (1, 1143)	0.9066828909972341
  (1, 1126)	0.0924884775100255
  (1, 1116)	0.2590522545706383
  (1, 1100)	0.1372435826249207
  (1, 1015)	0.12952612728531915
  (1, 999)	0.11090165546946365
  (1, 857)	0.10861559490216818
  (1, 765)	0.08331737044765954
  (1, 612)	0.12952612728531915
  (1, 28)	0.1372435826249207
  (2, 1146)	0.4658502098003352
  (2, 1098)	0.40665205359669604
  (2, 1046)	0.3849138264938751
  (2, 999)	0.18821848890686513
  (2, 838)	0.4658502098003352
  (2, 194)	0.4658502098003352
  (3, 843)	0.5884049558077298
  (3, 511)	0.6361579835182382
  (3, 105)	0.49908178486788374
  :	:
  (991, 305)	0.3496697883482917
  (991, 208)	0.22226362360991514
  (991, 117)	0.3081763120665512
  (992, 933)	0.13304696365353494
  (992, 604)	0.46888005988466913
  (992, 591)	0.11811090040087917
  (992, 513)	0.22417131222574282

In [110]:
print(fidtf.idf_[tf.vocabulary_['IT']])

KeyError: 'IT'

In [178]:
#multinomialNB will use the  actiation function according to the data 
from sklearn.naive_bayes import MultinomialNB

In [179]:
detec = MultinomialNB().fit(tf4, data['CourseName'])

In [181]:
print('Predict', detec.predict(tf4)[0])

Predict Financial Literacy 


In [182]:
print('Actual', data.CourseName[3])

Actual HIV/AIDS - Awareness & Prevention 


In [183]:
all_prediction = detec.predict(tf4)
# all_prediction

In [184]:
from sklearn.metrics import classification_report
print(classification_report(data['CourseName'], all_prediction))

                                                                                         precision    recall  f1-score   support

                                                    21 Days to Building a Web Business        1.00      1.00      1.00         1
                                                           3D Printing with Windows 10        1.00      1.00      1.00         1
                                                                         ACT Math Exam        1.00      1.00      1.00         1
                                               ALISON ABC IT - Computer Training Suite        1.00      1.00      1.00         1
                                           Accounting - Control and Monitoring of Cash        1.00      1.00      1.00         1
                                        Accounting - Measuring and Reporting Inventory        1.00      1.00      1.00         1
                                               Accounting - Merchandising Transactions        1.

c:\users\anand\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [13]:
import pandas as pd
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk import pos_tag, word_tokenize
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import svm
from sklearn.metrics import confusion_matrix

data = pd.read_csv("alsiondataset1.csv", encoding = "latin-1")[:995]
data = data[['CourseName', 'Column']]
data = data.rename(columns = {'CourseName': 'label', 'Column': 'text'})

lemmatizer = WordNetLemmatizer()
stopwords = set(stopwords.words('english'))

def review_messages(msg):
    # converting messages to lowercase
    msg = msg.lower()
    return msg

def alternative_review_messages(msg):
    # converting messages to lowercase
    msg = msg.lower()

    # uses a lemmatizer (wnpos is the parts of speech tag)
    # unfortunately wordnet and nltk uses a different set of terminology for pos tags
    # first, we must translate the nltk pos to wordnet
    nltk_pos = [tag[1] for tag in pos_tag(word_tokenize(msg))]
    msg = [tag[0] for tag in pos_tag(word_tokenize(msg))]
    wnpos = ['a' if tag[0] == 'J' else tag[0].lower() if tag[0] in ['N', 'R', 'V'] else 'n' for tag in nltk_pos]
    msg = " ".join([lemmatizer.lemmatize(word, wnpos[i]) for i, word in enumerate(msg)])

    # removing stopwords 
    msg = [word for word in msg.split() if word not in stopwords]

    return msg

# Processing text messages
data['text'] = data['text'].apply(review_messages)

# train test split 
X_train, X_test, y_train, y_test = train_test_split(data['text'], data['label'],test_size = 0.1, random_state = 1)

# training vectorizer
vectorizer = TfidfVectorizer()
X_train = vectorizer.fit_transform(X_train)

# training the classifier 
svm = svm.SVC(C=1000)
svm.fit(X_train, y_train)

# testing against testing set 
X_test = vectorizer.transform(X_test)
y_pred = svm.predict(X_test) 
print(confusion_matrix(y_test, y_pred))

# test against new messages 
def pred(msg):
    msg = vectorizer.transform([msg])
    prediction = svm.predict(msg)
    return prediction[0]


c:\users\anand\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
#predicting acording to the user input

In [14]:
pred('Office Skills Microsoft Office Software Tools')

'Microsoft Office 2010 - Revised 2018 '

In [17]:
pred('HIV Health')

'HIV/AIDS - Awareness & Prevention - Revised 2018 '

In [18]:
pred('Health Management	Workplace Safety')

'Drug-Free Workplace '